apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-commence-user
  labels:
    app: e-commence-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e-commence-user
  template:
    metadata:
      name: e-commence-user
      labels:
        app: e-commence-user
    spec:
      containers:
        - name: e-commence-user
          # TODO: 替换成动态修改与获取
          image: ccr.ccs.tencentyun.com/e-commence/user:v1.0.0
          imagePullPolicy: Always
          args:
            - /bin/user
            - -conf
            - /bin/configs
          ports:
            - containerPort: 30001
              protocol: TCP
              name: http-server
            - containerPort: 30002
              protocol: TCP
              name: grpc-server
          #livenessProbe:
          #  httpGet:
          #    path: /healthz
          #    port: 8080
          #  initialDelaySeconds: 10
          #  periodSeconds: 10
          #  timeoutSeconds: 5
          #  failureThreshold: 3
          #  successThreshold: 1
          #readinessProbe:
          #  httpGet:
          #    path: /readyz
          #    port: 8080
          #  initialDelaySeconds: 5
          #  periodSeconds: 5
          #  timeoutSeconds: 3
          #  failureThreshold: 3
          #  successThreshold: 1
      restartPolicy: Always

